install.packagess("plyr")
install.packages("dplyr")
install.packages("reshape")
install.packages("tm")
install.packages("SnowballC")
install.packages("ggplot2")
install.packages("RColorBrewer")
install.packages("wordcloud")

require("plyr")
require("dplyr")
require("reshape")
require("tm")
require("SnowballC")
require("ggplot2")
require("RColorBrewer")
require("wordcloud")
